name: qmusix
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  youtube_player_iframe: ^4.0.4
  http: ^1.1.0
  provider: ^6.0.5
  go_router: ^12.0.0
  flutter_native_splash: ^2.3.4
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/
